server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.239.128
aliyun:
  sms:
    accessKeyID: LTAIxo9ZQyltSHYL
    accessKeySecret: LawJXWPqLMvG69lzCcEOBoyvGvmE5G
    template_code: SMS_94700095
    sign_name: 李腾飞自己做短信测试